### ISSUE TITLE
Parallel review process

### ISSUE THREAD

**Issue by SoTrx** [cmendible/azqr#26]
## Describe the proposal

Hey guys, 
I came across this project and decided to give it a try. While playing with the project, I saw that the analyzers were run in a sequential manner. As a lot of the review process is API calls, the whole thing should mainly be I/O bound and would benefit greatly for a parallel approach

I'll link a PR as a follow up

**Comment by cmendible** [comment]
This is great @SoTrx thanks for your contribution.!

How was your experience? Any feedback?

**Comment by SoTrx** [comment]
I think it's a nice way to see some details about a Landing Zone.

Do you plan to implement some multi-resources reviews ? Something like a mardown rendered only if the user has some variant of a 3-tier application ?

**Comment by cmendible** [comment]
> Do you plan to implement some multi-resources reviews ?

Plans are to add resource specific best practice analysis, for instance for Azure Functions:

- If a Function App is found with VNET integration, does the subnet have the recommended size? 
- Are all Function Apps using a dedicated storage account?
- Are recommended Function Apps settings present?
- and more.
