### ISSUE TITLE
ubuntu release 0.7.3 crashes in WSL2 (ubuntu 20.04)

### ISSUE THREAD

**Issue by lopeg** [cmendible/azqr#28]
## Expected Behavior
Successfully run 
`./azqr-ubuntu-latest-amd64 -s "XXX" -g "YYY"`

## Actual Behavior

`2023/02/08 13:03:35 Analyzing SQL in Resource Group YYY
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfb1ff]

goroutine 86 [running]:
github.com/cmendible/azqr/internal/scanners.(*StorageScanner).Scan(0xc000382b40, {0x7fffaeff2edd, 0x1a})
        /home/runner/work/azqr/azqr/internal/scanners/st.go:50 +0x19f
main.reviewRunner.func1(0xc000153d00, {0x7fffaeff2edd, 0x1a})
        /home/runner/work/azqr/azqr/cmd/azqr/main.go:195 +0x102
created by main.reviewRunner
        /home/runner/work/azqr/azqr/cmd/azqr/main.go:189 +0x73`

**Comment by cmendible** [comment]
Hi it seem to be failing accessing the `access tier` of an Storage Account. Can you give me more info on the particular storage accounts?

**Comment by pamontag** [comment]
With the new build (windows) I have no more the st.go error and the assessment was completed. Thank you

![image](https://user-images.githubusercontent.com/19266001/217600424-44fae2a8-6253-4235-9669-24ce13ea6f9c.png)

**Comment by cmendible** [comment]
Great! I will release 0.7.4. 

Out of curiosity is the Storage Account an v1 or ADLS?

**Comment by pamontag** [comment]
![image](https://user-images.githubusercontent.com/19266001/217601494-65712776-1e20-49b3-910c-055544d05ba8.png)

**Comment by cmendible** [comment]
v1 was the culprit.

Thanks for the feedback!

**Comment by lopeg** [comment]
> @lopeg please download and try `azqr` from here: https://github.com/cmendible/azqr/actions/runs/4125206893 and let me know if it fixes the issue.

Fixed. Thank you!
