### ISSUE TITLE
Extend AKS report with SKU tier recommendations

### ISSUE THREAD

**Issue by Alvaromg45** [cmendible/azqr#37]
If the AKS is using a free SKU the report should include a recommendation message saying is not recommended for production environment, with a link to the official documentation: https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks?toc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#kubernetes-api-server-uptime-sla

**Comment by cmendible** [comment]
Closed in e2f3f8bda37e644b2ddfb6aed32aa6df19090488 and released in https://github.com/cmendible/azqr/releases/tag/v.0.10.0
