### ISSUE TITLE
[Application Gateway] Avoid showing recommendations when every resource of that type is properly configured

### ISSUE THREAD

**Issue by Alvaromg45** [cmendible/azqr#41]
## Expected Behavior

I have an Application Gateway with SKU Standard V2 that is using Availability Zones. I don't expect any recommendation to show in the report if the resource is properly configured.

## Actual Behavior

I got the following message after executing the tool:

_v2 SKU includes Zone Redundancy so an Application Gateway or WAF deployment can span multiple Availability Zones, removing the need to provision separate Application Gateway instances in each zone with a Traffic Manager.  

[Autoscaling and Zone-redundant Application Gateway v2 | Microsoft Docs](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-autoscaling-zone-redundant)_  

## Steps to Reproduce the Problem

Create an Application Gateway with SKU Standard V2 and configure Availability Zones for the resource. Then, run the tool and read the report.

**Comment by cmendible** [comment]
Perhaps we should rename the section to something like: **Best Practices** and show it regardless of the results of the scan.

@Alvaromg45 thoughts?

**Comment by Alvaromg45** [comment]
It would be better than nothing, but I think it would be a lost opportunity if we cannot match information about the real resources (that we gather during the scan process) with actual recommendations that can help you to increase the quality of your Azure Solution.
